[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "binaryen.py"
authors = [
    {name = "Jonathan Hargreaves", email = "jhargreaves189@gmail.com"},
]
description = "A Python wrapper for Binaryen"
requires-python = ">=3.11"
dependencies = [
    'cffi >= 1.15.1',
]
version = "0.0.1"

[project.optional-dependencies]
dev = ["black", "isort", "mkdocs", "pytest"]